### ISSUE TITLE
dockeri.co is down

### ISSUE THREAD

**Issue by mkenney** [retrohacker/dockeri.co#12]
It looks like a container or proxy needs to be bounced. I love the badge though, great work!

**Comment by retrohacker** [comment]
Thanks for the heads up! I need to get a pingdom style monitor setup for this, but haven't gotten around to it.

Just migrated back to Digital Ocean, should be up and running now :-)

**Comment by retrohacker** [comment]
(DNS may take a bit to propagate)

**Comment by mkenney** [comment]
Up for me, thank you!
