### ISSUE TITLE
dockeri.co is down

### ISSUE THREAD

**Issue by mkenney** [retrohacker/dockeri.co#13]
Fyi, looks like your DNS service is failing.

**Comment by jch254** [comment]
Pls pls fix this, I love your service and use it often 👍

**Comment by dpolyakov** [comment]
> This domain has expired and is now suspended.
http://www.dockeri.co/

**Comment by retrohacker** [comment]
Hey y'all, thanks for using this service :heart:

Just paid to renew the domain name, it should be back up soon. I set it to auto-renew, so this shouldn't happen again :smile:

**Comment by mkenney** [comment]
Looks good, thanks!

**Comment by jch254** [comment]
Champion! 👍
